// Automatically generated by @teamsupercell/typings-for-css-modules-loader.
// Please do not edit this file manually.
declare namespace NotFoundScssNamespace {
  export interface INotFoundScss {
    notFound: string;
  }
}

declare const NotFoundScssModule: NotFoundScssNamespace.INotFoundScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: NotFoundScssNamespace.INotFoundScss;
};

export = NotFoundScssModule;
