// Automatically generated by @teamsupercell/typings-for-css-modules-loader.
// Please do not edit this file manually.
declare namespace ParticlesListScssNamespace {
  export interface IParticlesListScss {
    expression: string;
    expressionLabel: string;
    isMobile: string;
    isVisible: string;
    list: string;
    listToggle: string;
    particle: string;
    particleHeading: string;
    particlesList: string;
  }
}

declare const ParticlesListScssModule: ParticlesListScssNamespace.IParticlesListScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ParticlesListScssNamespace.IParticlesListScss;
};

export = ParticlesListScssModule;
