// Automatically generated by @teamsupercell/typings-for-css-modules-loader.
// Please do not edit this file manually.
declare namespace LanguageSelectScssNamespace {
  export interface ILanguageSelectScss {
    languageSelect: string;
    selectedLanguage: string;
  }
}

declare const LanguageSelectScssModule: LanguageSelectScssNamespace.ILanguageSelectScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: LanguageSelectScssNamespace.ILanguageSelectScss;
};

export = LanguageSelectScssModule;
