// Automatically generated by @teamsupercell/typings-for-css-modules-loader.
// Please do not edit this file manually.
declare namespace AddParticleScssNamespace {
  export interface IAddParticleScss {
    expression: string;
    expressionsInputs: string;
    modalContent: string;
  }
}

declare const AddParticleScssModule: AddParticleScssNamespace.IAddParticleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: AddParticleScssNamespace.IAddParticleScss;
};

export = AddParticleScssModule;
